// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6e4470d56d9eda9fc1f58aa008a552b6397bc711a65e75502de56375a75bbd37")
